# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/workspace/Zybo-Master.xdc

# Block Designs: bd/SSD1306_example_bd/SSD1306_example_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SSD1306_example_bd || ORIG_REF_NAME==SSD1306_example_bd}]

# IP: bd/SSD1306_example_bd/ip/SSD1306_example_bd_processing_system7_0_0/SSD1306_example_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SSD1306_example_bd_processing_system7_0_0 || ORIG_REF_NAME==SSD1306_example_bd_processing_system7_0_0}]

# XDC: bd/SSD1306_example_bd/ip/SSD1306_example_bd_processing_system7_0_0/SSD1306_example_bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SSD1306_example_bd_processing_system7_0_0 || ORIG_REF_NAME==SSD1306_example_bd_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/SSD1306_example_bd/SSD1306_example_bd_ooc.xdc
